apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: shopkube
data:
  APP_NAME: "ShopKube"
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "shopkube"
  DB_USER: "shopkube_user"
  nginx.conf: |
    server {
        listen 80;
        location / { root /usr/share/nginx/html; }
        location /health {
            return 200 'ShopKube OK';
            add_header Content-Type text/plain;
        }
    }
